name = "AdaptiveABC"
uuid = "cdf71b62-2f9f-11e9-16f1-c99e795534db"
authors = ["Anthony Bowman <anthony.bowman10@imperial.ac.uk>", "Istvan Kleijn <istvan.kleijn16@imperial.ac.uk>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
